# -*- coding: utf-8 -*-
"""MAJOR PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FdWVDqosPkpZKesNsDzEDoNWaCak1xlx
"""

!pip install transformers scikit-learn nltk

import pandas as pd
import numpy as np
import torch
import nltk

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score

from transformers import DistilBertTokenizer, DistilBertModel

nltk.download('punkt')

from google.colab import files
uploaded = files.upload()

# Assuming the uploaded file is news_dataset.csv
# You might need to adjust the filename if it's different
import pandas as pd
df = pd.read_csv(list(uploaded.keys())[0])

df['content'] = df['title'] + " " + df['text']

X = df['content']
y = df['label']

df.head()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# MODEL 1: TF-IDF + Logistic Regression

tfidf = TfidfVectorizer(stop_words='english', max_df=0.7)

X_train_filled = X_train.fillna('')
X_test_filled = X_test.fillna('')

X_train_tfidf = tfidf.fit_transform(X_train_filled)
X_test_tfidf = tfidf.transform(X_test_filled)

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_tfidf, y_train)

pred_tfidf = lr.predict(X_test_tfidf)

print("TF-IDF Accuracy:", accuracy_score(y_test, pred_tfidf))
print("TF-IDF F1 Score:", f1_score(y_test, pred_tfidf))

#MODEL 2: DistilBERT
from transformers import DistilBertTokenizer, DistilBertModel

tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
bert_model = DistilBertModel.from_pretrained('distilbert-base-uncased')
bert_model.eval()

#BERT Embedding Function
def get_embeddings(texts):
    embeddings = []

    for text in texts:
        inputs = tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            padding=True,
            max_length=128
        )

        with torch.no_grad():
            outputs = bert_model(**inputs)

        emb = outputs.last_hidden_state.mean(dim=1).squeeze().numpy()
        embeddings.append(emb)

    return np.array(embeddings)

#Generate Embeddings
X_train_bert = get_embeddings(X_train_filled.tolist()[:1000])
X_test_bert = get_embeddings(X_test_filled.tolist()[:300])

y_train_small = y_train.iloc[:1000]
y_test_small = y_test.iloc[:300]

#Train BERT Classifier
bert_clf = LogisticRegression(max_iter=1000)
bert_clf.fit(X_train_bert, y_train_small)

pred_bert = bert_clf.predict(X_test_bert)

print("BERT Accuracy:", accuracy_score(y_test_small, pred_bert))
print("BERT F1 Score:", f1_score(y_test_small, pred_bert))

#MODEL 3: HYBRID (TF-IDF + BERT)
tfidf_train_small = X_train_tfidf[:1000].toarray()
tfidf_test_small = X_test_tfidf[:300].toarray()


hybrid_train = np.hstack((tfidf_train_small, X_train_bert))
hybrid_test = np.hstack((tfidf_test_small, X_test_bert))


hybrid_model = LogisticRegression(max_iter=1000)
hybrid_model.fit(hybrid_train, y_train_small)

pred_hybrid = hybrid_model.predict(hybrid_test)

print("Hybrid Accuracy:", accuracy_score(y_test_small, pred_hybrid))
print("Hybrid F1 Score:", f1_score(y_test_small, pred_hybrid))

print("\n📊 FINAL RESULTS")
print("TF-IDF Accuracy:", accuracy_score(y_test, pred_tfidf))
print("BERT Accuracy:", accuracy_score(y_test_small, pred_bert))
print("Hybrid Accuracy:", accuracy_score(y_test_small, pred_hybrid))

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_tfidf, y_train)

import pickle

pickle.dump(lr, open('model.pkl', 'wb'))
pickle.dump(tfidf, open('tfidf.pkl', 'wb'))

from google.colab import files

files.download('model.pkl')
files.download('tfidf.pkl')